<?php // vim: expandtab sw=4 ts=4 sts=4:

/**
 * Xataface Query
 *
 *
 * @version     2.0
 * @copyright   2001-2012 Universite catholique de Louvain (UCL)
 * @author      Frederic Minne <frederic.minne@uclouvain.be>
 * @license     http://www.fsf.org/licensing/licenses/agpl-3.0.html
 *              GNU AFFERO GENERAL PUBLIC LICENSE version 3
 */

class Xataface_Query
{
    protected $url;
    protected $limit = 1000000;
    protected $offset = 0;
    
    public function __construct( $baseUrl, $queryParameters = null )
    {
        $this->url = new Url( $baseUrl );
        
        if ( is_array( $queryParameters ) && ! empty( $queryParameters ) )
        {
            $this->url->addParamList( $queryParameters, true );
        }
    }
    
    public function getUrl()
    {
        return $this->url;
    }
    
    public function setQueryParameters( $table, $queryParameters = null )
    {
        $this->url->replaceParam( '-table', $table, true );
        
        if ( is_array( $queryParameters ) && ! empty( $queryParameters ) )
        {
            $this->url->addParamList( $queryParameters, true );
        }
    }
    
    public function setLimit( $limit )
    {
        $this->limit = $limit;
    }
    
    public function setOffset( $offset )
    {
        $this->offset = $offset;
    }
    
    /**
     * Get XML data from URL
     * @param string $sourceUrl
     * @return string XML data retrieved from the URL
     */
    public function getXmlResponse()
    {
        $this->url->replaceParam('-action','export_xml',true);
        
        $this->url->replaceParam('-limit',$this->limit,true);
        
        $this->url->replaceParam('-offset',$this->offset,true);
        
        $httpRequest = new HttpRequest;
        
        $response = $httpRequest->get( $this->url );
        
        // workaround for incomplete XML files generated by xataface
        if ( preg_match('!<record>!', $response) 
            && !preg_match('!</record>!', $response) )
        {
            $response .= "\n</record>\n";
        }
        
        return $response;
    }
}
